"""Added a  volumne column and renamed too

Revision ID: 10dbcf9f7deb
Revises: e36faa0b4ca8
Create Date: 2025-05-28 14:47:33.473992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dbcf9f7deb'
down_revision = 'e36faa0b4ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_okha_port', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume_external_plot', sa.Float(), nullable=True))
        batch_op.drop_column('volume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.FLOAT(), nullable=True))
        batch_op.drop_column('volume_external_plot')
        batch_op.drop_column('volume_okha_port')

    # ### end Alembic commands ###
