"""Added adv note columns

Revision ID: 27e68e902b56
Revises: 851ad8bb6bc2
Create Date: 2025-05-22 10:02:31.221346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e68e902b56'
down_revision = '851ad8bb6bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adv_penalty_note', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('adv_base_note', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_column('adv_base_note')
        batch_op.drop_column('adv_penalty_note')

    # ### end Alembic commands ###
