"""Added kacha column to PortArea

Revision ID: 39270cbd91ed
Revises: 
Create Date: 2025-05-06 15:51:16.895181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39270cbd91ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allotment_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kacha_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paka_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kacha_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paka_penalty', sa.Float(), nullable=True))
        batch_op.drop_column('rate')
        batch_op.drop_column('penalty_per_day')

    with op.batch_alter_table('port_area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kacha', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_area', schema=None) as batch_op:
        batch_op.drop_column('kacha')

    with op.batch_alter_table('allotment_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_per_day', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rate', sa.FLOAT(), nullable=True))
        batch_op.drop_column('paka_penalty')
        batch_op.drop_column('kacha_penalty')
        batch_op.drop_column('paka_rate')
        batch_op.drop_column('kacha_rate')

    # ### end Alembic commands ###
