"""updated the table to store the total tonnage

Revision ID: 39688596fc2c
Revises: 7c8dce4a80a0
Create Date: 2025-05-16 14:07:17.114090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39688596fc2c'
down_revision = '7c8dce4a80a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_stats', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
