"""Added TaxRate table

Revision ID: 4d52b37c9aa2
Revises: de59d59de553
Create Date: 2025-05-08 12:16:54.191381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d52b37c9aa2'
down_revision = 'de59d59de553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rate')
    # ### end Alembic commands ###
