"""Added from date column to 3 tables

Revision ID: 5a30d7f646d4
Revises: 27e68e902b56
Create Date: 2025-05-22 11:52:35.926602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a30d7f646d4'
down_revision = '27e68e902b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allotment_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_date', sa.Date(), nullable=True))

    with op.batch_alter_table('port_area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_date', sa.Date(), nullable=True))

    with op.batch_alter_table('tax_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_rate', schema=None) as batch_op:
        batch_op.drop_column('from_date')

    with op.batch_alter_table('port_area', schema=None) as batch_op:
        batch_op.drop_column('from_date')

    with op.batch_alter_table('allotment_rate', schema=None) as batch_op:
        batch_op.drop_column('from_date')

    # ### end Alembic commands ###
