"""Add total_amount to Port

Revision ID: 851ad8bb6bc2
Revises: acfd5d570f5e
Create Date: 2025-05-20 10:36:57.258309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851ad8bb6bc2'
down_revision = 'acfd5d570f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
