"""added col to monthly sales

Revision ID: acfd5d570f5e
Revises: 39688596fc2c
Create Date: 2025-05-16 16:28:07.311901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfd5d570f5e'
down_revision = '39688596fc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_ton', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_stats', schema=None) as batch_op:
        batch_op.drop_column('cost_per_ton')

    # ### end Alembic commands ###
