"""renamed a col in item having total bl quantity

Revision ID: c1bf68580dff
Revises: 10dbcf9f7deb
Create Date: 2025-05-28 17:33:34.442203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bf68580dff'
down_revision = '10dbcf9f7deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_bl', sa.Float(), nullable=True))
        batch_op.drop_column('volume_external_plot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_external_plot', sa.FLOAT(), nullable=True))
        batch_op.drop_column('volume_bl')

    # ### end Alembic commands ###
