"""deleted columns from vessel table

Revision ID: de59d59de553
Revises: 39270cbd91ed
Create Date: 2025-05-07 14:25:26.339389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de59d59de553'
down_revision = '39270cbd91ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('sgst')
        batch_op.drop_column('base_amount')
        batch_op.drop_column('open_plot_rent_extra')
        batch_op.drop_column('month')
        batch_op.drop_column('days')
        batch_op.drop_column('from_date')
        batch_op.drop_column('plot_rent_per_mt')
        batch_op.drop_column('plot_area')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('cgst')
        batch_op.drop_column('plot_no')
        batch_op.drop_column('to_date')
        batch_op.drop_column('open_plot_rent_per_10sqm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_plot_rent_per_10sqm', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('to_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('plot_no', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cgst', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('plot_area', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('plot_rent_per_mt', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('from_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('month', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('open_plot_rent_extra', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('base_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sgst', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
