"""Added material table

Revision ID: e36faa0b4ca8
Revises: 5a30d7f646d4
Create Date: 2025-05-23 11:20:13.233695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36faa0b4ca8'
down_revision = '5a30d7f646d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    # ### end Alembic commands ###
