"""added pr number

Revision ID: ea3ee2557de0
Revises: 4d52b37c9aa2
Create Date: 2025-05-09 16:11:10.385279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3ee2557de0'
down_revision = '4d52b37c9aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('purchase_order')

    # ### end Alembic commands ###
